#!/bin/bash

DIR=$(pwd)
PROGRAM="simulator"

OPTIND=1
RANKS=1
THREADS=1

while getopts "n:p:" opt; do
    case "$opt" in
    n)  RANKS=$OPTARG
        ;;
    p)  THREADS=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))
[ "$1" = "--" ] && shift

echo "Running $PROGRAM with"
echo "  RANKS=$RANKS, THREADS=$THREADS"
mpirun -N $RANKS "$DIR/$PROGRAM" -p $THREADS

echo "Generating Plots"
Rscript plot_birds.R --vanilla

echo "Creating .gif"
convert -delay 12x100 Rplots.pdf Rplots.gif

echo "Finished!"
