#!/bin/bash

DIR=$(pwd)
PROGRAM="simulator"

NODES=1

if [ "$1" ]; then
   NODES="$1"
fi


RANKS=$((NODES * 64))
THREADS=1

echo "Running $PROGRAM with"
echo "  NODES=$NODES, RANKS=$RANKS, THREADS=$THREADS"

srun --ntasks $RANKS --overcommit -o "$RANKS.log" "$DIR/$PROGRAM" -p $THREADS

RANKS=$((NODES * 32))
THREADS=2

echo "Running $PROGRAM with"
echo "  NODES=$NODES, RANKS=$RANKS, THREADS=$THREADS"

srun --ntasks $RANKS --overcommit -o "$RANKS.log" --open-mode=append "$DIR/$PROGRAM" -p $THREADS

RANKS=$((NODES * 16))
THREADS=4

echo "Running $PROGRAM with"
echo "  NODES=$NODES, RANKS=$RANKS, THREADS=$THREADS"

srun --ntasks $RANKS --overcommit -o "$RANKS.log" --open-mode=append "$DIR/$PROGRAM" -p $THREADS

RANKS=$((NODES * 8))
THREADS=8

echo "Running $PROGRAM with"
echo "  NODES=$NODES, RANKS=$RANKS, THREADS=$THREADS"

srun --ntasks $RANKS --overcommit -o "$RANKS.log" --open-mode=append "$DIR/$PROGRAM" -p $THREADS

RANKS=$((NODES * 4))
THREADS=16

echo "Running $PROGRAM with"
echo "  NODES=$NODES, RANKS=$RANKS, THREADS=$THREADS"

srun --ntasks $RANKS --overcommit -o "$RANKS.log" --open-mode=append "$DIR/$PROGRAM" -p $THREADS

RANKS=$((NODES * 2))
THREADS=32

echo "Running $PROGRAM with"
echo "  NODES=$NODES, RANKS=$RANKS, THREADS=$THREADS"

srun --ntasks $RANKS --overcommit -o "$RANKS.log" --open-mode=append "$DIR/$PROGRAM" -p $THREADS

RANKS="$NODES"
THREADS=64

echo "Running $PROGRAM with"
echo "  NODES=$NODES, RANKS=$RANKS, THREADS=$THREADS"

srun --ntasks $RANKS --overcommit -o "$RANKS.log" --open-mode=append "$DIR/$PROGRAM" -p $THREADS

echo "Finished!"
